services:
  postgres:
      image: postgres:17-alpine
      restart: always
      
      environment:
        POSTGRES_DB: concursdb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d concursdb"]
        interval: 5s
        timeout: 5s
        retries: 5
        start_period: 10s
        

  itmoparser:
    image: itmoparser
    restart: always
    depends_on:
      postgres:
       condition: service_healthy
  
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
  

  