// <auto-generated />
using System.Collections.Generic;
using ITMOParser;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ITMOParser.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260716200456_InitialMigration1")]
    partial class InitialMigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ITMOParser.Application", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AbiturientId")
                        .HasColumnType("integer");

                    b.Property<bool>("Advantage")
                        .HasColumnType("boolean");

                    b.Property<bool>("Confirmation")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<int>>("Exams")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("IndividualAchievements")
                        .HasColumnType("integer");

                    b.Property<bool?>("Passes")
                        .HasColumnType("boolean");

                    b.Property<int>("PointsBase")
                        .HasColumnType("integer");

                    b.Property<int>("PointsFinal")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("itmo");
                });
#pragma warning restore 612, 618
        }
    }
}
